# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeocodeCN
                                 A QGIS plugin
 crs getter
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-03
        copyright            : (C) 2022 by ShihanW
        email                : 3443327820@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeocodeCN class from file GeocodeCN.
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GeocodeCN import GeocodeCN
    return GeocodeCN(iface)
